# Change these first
owner: AventiumSoftworks # Your GitHub organization or username, where this repository lives
repo: helios-status-page # The name of this repository

sites:
  - name: Mojang Multiplayer Session Service
    url: http://session.minecraft.net
    expectedStatusCodes:
      - 404
  - name: Mojang Authserver
    url: https://authserver.mojang.com/
  - name: Minecraft Skins
    url: https://textures.minecraft.net
    expectedStatusCodes:
      - 400
  - name: "Mojang's Public API"
    url: https://api.mojang.com/
  - name: Minecraft.net website
    url: https://www.minecraft.net/en-us
    expectedStatusCodes:
      - 403
  - name: Mojang Accounts Website
    url: https://account.mojang.com/login
    expectedStatusCodes:
      - 403
      - 200
  - name: Microsoft OAuth Server
    url: https://login.microsoftonline.com/consumers/oauth2/v2.0/token
  - name: Xbox Live auth server
    url: https://user.auth.xboxlive.com/user/authenticate
    expectedStatusCodes:
      - 405
  - name: Xbox Live Gatekeeper
    url: https://xsts.auth.xboxlive.com/xsts/authorize
    expectedStatusCodes:
      - 405
  - name: Microsoft Minecraft API
    url: https://api.minecraftservices.com/authentication/login_with_xbox
    expectedStatusCodes:
      - 401
      - 403
  - name: Microsoft Minecraft Profile
    url: https://api.minecraftservices.com/minecraft/profile
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: aventiumsoftworks.github.io
  baseUrl: /helios-status-page
  logoUrl: https://github.com/dscalzi/HeliosLauncher/raw/master/app/assets/images/SealCircle.png
  name: Helios Status Page
  introTitle: "This page is used by Helios Launcher to get Mojang status."
  introMessage: We are not Mojang/Microsoft
  navbar:
    - title: Home
      href: /helios-status-page
    - title: Helios Launcher source code
      href: https://github.com/dscalzi/HeliosLauncher

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
